apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hospital-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: hospital.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hospital-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hospital-backend
            port:
              number: 8080