apiVersion: v1
kind: Secret
metadata:
  name: hospital-secrets
type: Opaque
stringData:
  jwt-secret: "HospitalManagementSecretKey2024ForJWTTokenGeneration"
  postgres-password: "postgres"
  redis-password: ""